import { Link } from "react-router-dom";
export default function AffiliateTerms() {
  return <main className="max-w-3xl mx-auto px-6 py-14 space-y-7">
    <Link to="/programa-creadores" className="text-primary underline">← Programa de creadores</Link>
    <h1 className="text-3xl font-bold">Condiciones del programa de afiliados</h1>
    <p>Versión del 19 de septiembre de 2026. Estas condiciones describen las comisiones por recomendar suscripciones de TokXray.</p>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Comisión y duración</h2><p>El afiliado recibe el 30% del importe efectivamente cobrado por las suscripciones de sus referidos directos, después de descuentos y sin impuestos. Una renovación de $30 USD genera $9 USD de comisión; un primer pago de $15 USD genera $4.50 USD. No hay un límite de seis meses: se generan comisiones mientras el referido mantenga su suscripción y sus pagos elegibles.</p><p>No se paga por registrar personas, reclutar afiliados ni por los referidos de otros afiliados. Los ingresos dependen de suscripciones reales y no están garantizados.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Descuento y atribución</h2><p>El descuento es del 50% en el primer mes para clientes nuevos con un código válido. Las renovaciones son de $30 USD mensuales hasta cancelar; los impuestos aplicables se muestran al pagar. No se acumulan descuentos.</p><p>El enlace conserva el código en el navegador para completar el registro. La atribución se valida en el servidor y queda vinculada a la cuenta. No se permite cambiar de afiliado para reclamar comisiones sobre pagos anteriores, referirse a uno mismo ni usar cuentas falsas.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Cobro de comisiones</h2><p>El mínimo de retiro es $50 USD de saldo disponible. Los pagos se procesan semanalmente mediante Stripe, sujetos a una cuenta de cobro verificada y habilitada. La llegada al banco depende de Stripe y de la entidad bancaria. El saldo inferior al mínimo se acumula para futuros periodos.</p><p>Los pagos fallidos, cuentas gratuitas y cobros reembolsados no generan comisiones. Los reembolsos o contracargos pueden descontarse del saldo; los importes en revisión no están disponibles para retiro.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Contenido y acceso promocional</h2><p>Debes explicar con claridad tu relación de afiliación y evitar prometer resultados garantizados. El acceso gratuito a cambio de contenido requiere un acuerdo separado que indique entregables y duración; no constituye un sueldo ni un pago fijo por videos.</p></section>
    <p>Consultas: <a className="text-primary underline" href="mailto:contacto@tokxray.com">contacto@tokxray.com</a>. También aplican los <Link className="text-primary underline" to="/terms">términos generales</Link> y la <Link className="text-primary underline" to="/refund-policy">política de reembolsos</Link>.</p>
  </main>;
}
